/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PharmaStore {
  'lat' : number,
  'lng' : number,
  'hours' : string,
  'area' : string,
  'name' : string,
  'outOfStock' : Array<string>,
  'distance' : number,
  'availableMeds' : Array<string>,
  'address' : string,
  'notes' : string,
  'lowStockMeds' : Array<string>,
  'phone' : string,
}
export interface _SERVICE {
  'addPharma' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      number,
      number,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      string,
    ],
    undefined
  >,
  'getPharmas' : ActorMethod<[], Array<PharmaStore>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];