/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PharmaStore = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'hours' : IDL.Text,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'outOfStock' : IDL.Vec(IDL.Text),
  'distance' : IDL.Float64,
  'availableMeds' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'lowStockMeds' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPharma' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getPharmas' : IDL.Func([], [IDL.Vec(PharmaStore)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PharmaStore = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'hours' : IDL.Text,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'outOfStock' : IDL.Vec(IDL.Text),
    'distance' : IDL.Float64,
    'availableMeds' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'lowStockMeds' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addPharma' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getPharmas' : IDL.Func([], [IDL.Vec(PharmaStore)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };